# Generated by Django 3.2 on 2021-06-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('address1', models.CharField(blank=True, max_length=250)),
                ('address2', models.CharField(max_length=250)),
                ('mobilenumber', models.IntegerField(blank=True, max_length=20)),
                ('post', models.IntegerField(blank=True, max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
