# Generated by Django 3.2 on 2021-06-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobilenumber',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='post',
            field=models.IntegerField(blank=True),
        ),
    ]
