# Generated by Django 3.2 on 2021-06-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0009_auto_20210626_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Success', 'Success')], default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Placed', 'Placed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Placed', max_length=20),
        ),
    ]
