# Generated by Django 3.2 on 2021-06-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0010_auto_20210626_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Placed', 'Placed'), ('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Delivered', 'Delivered')], default='Placed', max_length=20),
        ),
    ]
