# Generated by Django 3.2 on 2021-06-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0011_auto_20210626_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Pending', 'Pending'), ('Success', 'Success')], default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Returned', 'Returned')], default='Placed', max_length=20),
        ),
    ]
