# Generated by Django 3.2 on 2021-07-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0014_auto_20210630_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userimage',
            field=models.ImageField(default=3, upload_to='photos/productimages'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Success', 'Success')], default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Placed', 'Placed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped')], default='Placed', max_length=20),
        ),
    ]
