# Generated by Django 3.2 on 2021-07-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0015_auto_20210702_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Placed', 'Placed'), ('Cancelled', 'Cancelled')], default='Placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userimage',
            field=models.ImageField(blank=True, null=True, upload_to='photos/productimages'),
        ),
    ]
