# Generated by Django 3.2 on 2021-07-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0016_auto_20210702_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Pending', 'Pending'), ('Success', 'Success')], default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Delivered', 'Delivered'), ('Placed', 'Placed')], default='Placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userimage',
            field=models.ImageField(blank=True, default='user/images/user.png', null=True, upload_to='photos/productimages'),
        ),
    ]
