# Generated by Django 3.2 on 2021-07-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0020_auto_20210706_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Returned', 'Returned'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped')], default='Placed', max_length=20),
        ),
    ]
