# Generated by Django 3.2 on 2021-07-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0024_auto_20210708_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped')], default='Placed', max_length=20),
        ),
    ]
