# Generated by Django 3.2 on 2021-07-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0028_auto_20210712_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Returned', 'Returned')], default='Placed', max_length=20),
        ),
    ]
