# Generated by Django 3.2 on 2021-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0029_auto_20210712_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Placed', 'Placed')], default='Placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num',
            field=models.CharField(max_length=15),
        ),
    ]
