# Generated by Django 3.2 on 2021-07-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0030_auto_20210715_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Placed', 'Placed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
