# Generated by Django 3.2 on 2021-11-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zehak', '0031_auto_20210719_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Placed', 'Placed')], default='Placed', max_length=20),
        ),
    ]
