# Generated by Django 3.2 on 2021-06-09 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('week8', '0003_editproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='editproduct',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='week8.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='productname',
            field=models.CharField(default='ggg', max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(default='s', to='week8.Size'),
        ),
    ]
