# Generated by Django 3.2 on 2021-06-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week8', '0004_auto_20210609_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='newprice',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='productname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
