# Generated by Django 3.2 on 2021-11-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week8', '0013_auto_20210708_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditProduct',
        ),
    ]
